SELECT DISTINCT QUESTAO.* FROM QUESTAO
INNER JOIN TURMA
ON TURMA.ID = QUESTAO.TURMA_ID
INNER JOIN CURSOTURMA
ON TURMA.ID = CURSOTURMA.turma_id
INNER JOIN CURSO
ON CURSO.ID = CURSOTURMA.curso_id
INNER JOIN ALUNO
ON ALUNO.curso_id = CURSO.ID
INNER JOIN MATRICULA
ON MATRICULA.aluno_id = ALUNO.usuario_ptr_id
LEFT JOIN RESPOSTA 
ON RESPOSTA.questao_id = QUESTAO.ID
WHERE RESPOSTA.ID IS NULL AND DATA_LIMITE_ENTREGA <= '2017-11-19' AND ALUNO.usuario_ptr_id = 3