# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='celular2',
        ),
    ]
