# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171109_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursoTurmas', to='core.Curso')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursoTurmas', to='core.Turma')),
            ],
            options={
                'db_table': 'CursoTurma',
            },
        ),
    ]
