from .submodels.Curso import Curso
from .submodels.GradeCurricular import GradeCurricular
from .submodels.Turma import Turma
from .submodels.Professor import Professor
from .submodels.Disciplina import Disciplina
from .submodels.PeriodoDisciplina import PeriodoDisciplina
from .submodels.DisciplinaOfertada import DisciplinaOfertada
from .submodels.Aluno import Aluno
from .submodels.Questao import Questao
from .submodels.ArquivosQuestao import ArquivosQuestao
