from .Curso import Curso
from .GradeCurricular import GradeCurricular
from .Turma import Turma
from .Professor import Professor
from .Disciplina import Disciplina
from .Periodo import Periodo
from .DisciplinaOfertada import DisciplinaOfertada
from .Aluno import Aluno
from .Questao import Questao
from .ArquivosQuestao import ArquivosQuestao
from .ArquivosResposta import ArquivosResposta
from .Resposta import Resposta
from .Candidato import Candidato
from .ArquivosFoto import ArquivosFoto
from .Usuario import Usuario
