from .painelProfessor import painelProfessor
#from .Contato import *
from .turma import *
from .matricula import *
from .questao import *
from .questoes import *
from .exerciciosRecebidos import *
from .turmasPendentes import *
from .exerciciosPendentes import *
from .exercicios import *